name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        mkdir /go/bin
        export PATH=$PATH:/go/bin
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
        CGO_ENABLED=0 go build -ldflags '-s' -installsuffix cgo -o /go/bin/eve.a
        go build
        ./insider -tech javascript -target . 
